# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            零零陆伍
tagline:          夏日手帐
url:              http://0065paula.github.io/blog
paginate:         1
baseurl:          /blog/
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://0065paula.github.io/blog/

# This is the list of pages to incldue in the header of the website.
pages_list:       
  关于: '/blog/about'
  存档: '/blog/archive'